#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 27 15:40:33 2018

@author: phoebeliu
"""

import pandas as pd
import numpy as np
import config 
import pickle
import dash
import dash_core_components as dcc
import dash_html_components as html
import pandas as pd
import plotly.graph_objs as go

app = dash.Dash()

cluster_definition = pd.read_csv('./'+config.FILE_FOLDER+'/'+config.OUTPUT_FILENAME,sep=',',encoding='utf-8')
cluster_definition['CLUSTER_ID'] = cluster_definition['CLUSTER_ID'].astype('str')
document_vector = pd.DataFrame(pickle.load( open( "document_vector.p", "rb" ) ),columns=['x','y'])

df = pd.concat([cluster_definition,document_vector],axis=1)


app.layout = html.Div([
    dcc.Graph(
        id='life-exp-vs-gdp',
        figure={
            'data': [
                go.Scatter(
                    x=df[df['CLUSTER_ID'] == i]['x'],
                    y=df[df['CLUSTER_ID'] == i]['y'],
                    text=df[df['CLUSTER_ID'] == i]['CLUSTER_ID'].map(str) + ": "+df[df['CLUSTER_ID'] == i]['SPEECH'].map(str) ,
                    mode='markers',
                    opacity=0.7,
                    marker={
                        'size': 15,
                        'line': {'width': 0.5, 'color': 'white'}
                    },
                    name=i
                ) for i in df.CLUSTER_ID.unique()
            ],
            'layout': go.Layout(
                xaxis={'title': 'X'},
                yaxis={'title': 'Y'},
                margin={'l': 40, 'b': 40, 't': 10, 'r': 10},
                legend={'x': 0, 'y': 1},
                hovermode='closest'
            )
        }
    )
])

if __name__ == '__main__':
    app.run_server()